### ISSUE TITLE
Mariadb support

### ISSUE THREAD

**Issue by luizlinux** [neilmunday/Salt-Minion-Inventory#28]
Is MariaDB supported out of the box, or some modifications is required for that?

**Comment by luizlinux** [comment]
fggy:~/Salt-Minion-Inventory # mysql -u root < database.sql
ERROR 1046 (3D000) at line 4: No database selected
fggy:~/Salt-Minion-Inventory #

**Comment by neilmunday** [comment]
MariaDB/MySQL PHP and Python packages need to be installed on the server(s) running the Salt runner module and on the web server (both can be run on the same server or on separate ones).

Please see the README for all requirements.
