### ISSUE TITLE
inventory.audit' is not available

### ISSUE THREAD

**Issue by Debbyanne** [neilmunday/Salt-Minion-Inventory#36]
**Salt Master**
OS version: Debian 10
SaltStack version: 3003

**Salt Minions**
OS version: Debian 10
SaltStack version: 3003

**Issue description:**
I have followed the installation instructions however when I run the command: salt '*' inventory.audit force=True all I receive is

`'inventory.audit' is not available.`

The salt master logs state:
[salt.utils.reactor:443 ][ERROR   ][2335] Reactor 'inventory_present' failed to execute runner 'inventory.present': function not available

I have ensured that all the python modules are loaded and the database tables populated but im still having little success, in addressing this issue. Are you able to advise or point me in towards what action is required to address this.

**Comment by neilmunday** [comment]
Hi @Debbyanne. I take it you managed to resolve the issue?
