### ISSUE TITLE
Initial Setup issues.  

### ISSUE THREAD

**Issue by mdtabrezpasha** [neilmunday/Salt-Minion-Inventory#38]
**Salt Master**

OS version: 22.04 Ubuntu Server
SaltSatck version: 3005

**Salt Minions**

OS version: Windows
SaltStack version: 3004

**Issue description:**
error in WEB Gui & inventory.audit missing  
![image](https://user-images.githubusercontent.com/50145580/231556631-97292d66-8ce9-491b-89ed-1a9896e1b8c6.png)

![image](https://user-images.githubusercontent.com/50145580/231556816-a864b578-c00a-4e51-af66-2e3324ade856.png)

**Comment by neilmunday** [comment]
Hi,

For the DataTables Ajax error, please can you tell me what is being returned by browsing to the URL: `json/minions.json.php` on your web server under your Salt Minion Inventory web site please?

For the `inventory.audit is not available` error, I see you are using Windows minions. The use of Windows minions with Salt Minion Inventory is experimental and not thoroughly tested (I do not have the ability to test Windows minions unfortunately). To debug this further, on your Windows minions try running the `inventory.py` script that has been installed onto them, e.g. `python3 inventory.py`. If this fails to execute then this could point to an issue with your Windows Python installation.

**Comment by mdtabrezpasha** [comment]
HI Niel, i tried browsing the url json/minions.json.php
and for windows i havent installed python3 on it and inventory.py is not copied either, where do i place the inventory.py script on the windows minion?

![image](https://user-images.githubusercontent.com/50145580/231614464-e58b3456-60cd-4cca-a861-306375773b35.png)

**Comment by neilmunday** [comment]
For the HTTP 500 error, are there any errors in the web server's logs, e.g. PHP errors?

For the Windows minions, SaltStack will deploy `inventory.py` to every minion. On Linux minions, the file is located at: `/srv/salt/_modules/`. It should be in the equivalent `_modules` directory as part of the SaltStack installation.

**Comment by neilmunday** [comment]
Closing issue. Will re-open in the future if requested information is provided.
