### ISSUE TITLE
Salt 3006 OneDir breaks with missing MySQLdb module: Won't load the reactor

### ISSUE THREAD

**Issue by felimwhiteley** [neilmunday/Salt-Minion-Inventory#39]
Switching log_level to debug produces the following error:

May 26 10:28:57 gla-ccs salt-master[2473325]: [DEBUG   ] Failed to import runners inventory:
May 26 10:28:57 gla-ccs salt-master[2473325]: Traceback (most recent call last):
May 26 10:28:57 gla-ccs salt-master[2473325]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 772, in _load_module
May 26 10:28:57 gla-ccs salt-master[2473325]:     mod = self.run(spec.loader.load_module)
May 26 10:28:57 gla-ccs salt-master[2473325]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1232, in run
May 26 10:28:57 gla-ccs salt-master[2473325]:     return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
May 26 10:28:57 gla-ccs salt-master[2473325]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1247, in _run_as
May 26 10:28:57 gla-ccs salt-master[2473325]:     return _func_or_method(*args, **kwargs)
May 26 10:28:57 gla-ccs salt-master[2473325]:   File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
May 26 10:28:57 gla-ccs salt-master[2473325]:   File "<frozen importlib._bootstrap_external>", line 1063, in load_module
May 26 10:28:57 gla-ccs salt-master[2473325]:   File "<frozen importlib._bootstrap_external>", line 888, in load_module
May 26 10:28:57 gla-ccs salt-master[2473325]:   File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
May 26 10:28:57 gla-ccs salt-master[2473325]:   File "<frozen importlib._bootstrap>", line 719, in _load
May 26 10:28:57 gla-ccs salt-master[2473325]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
May 26 10:28:57 gla-ccs salt-master[2473325]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
May 26 10:28:57 gla-ccs salt-master[2473325]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
May 26 10:28:57 gla-ccs salt-master[2473325]:   File "/var/lib/salt/runners/inventory.py", line 36, in <module>
May 26 10:28:57 gla-ccs salt-master[2473325]:     import MySQLdb
May 26 10:28:57 gla-ccs salt-master[2473325]: ModuleNotFoundError: No module named 'MySQLdb'

It can be solved by making sure the system has the MySQL dev tools on Ubuntu/Debian with:
sudo apt install libmysqlclient-dev

Then running 
sudo salt-pip install configparser
sudo salt-pip install mysqlclient

Which installs the missing libraries into the OneDir python3.10

**Comment by neilmunday** [comment]
Thank you for supplying the above information @felimwhiteley. I have updated the README.
